on:

  schedule:
    - cron: '0 12 * * *'

  push:
    branches-ignore:
      - 'gh-pages'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - uses: Roberbg97/baseball_cubans_news_generation@master

      - name: deploy
        run: |
          git config --global user.name 'Roberbg97'
          git config --global user.email 'roberbg97@gmail.com'
          git add .
          git commit -am "Deploy apis"
          git push -f --set-upstream origin master
