on:

  schedule:
    - cron: '0 * * * *'

  push:
    branches-ignore:
      - 'gh-pages'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: Roberbg97/baseball_cubans_news_generation@master

      - name: Set env
        run: echo ::set-env name=UPDATED::$(python -c "import os;print(open('UPDATED').read(),end='');os.remove('UPDATED')")

      - name: show UPDATE var
        run: |
          echo "UPDATED"
          echo ${{env.UPDATED}}
          echo "conditions"
          echo ${{env.UPDATED==0}}
          echo ${{env.UPDATED==1}}

      - name: deploy
        if: ${{env.UPDATE==0}}
        run: |
          git config --global user.name 'Roberbg97'
          git config --global user.email 'roberbg97@gmail.com'
          git add .
          git commit -am "Deploy apis"
          git push -f --set-upstream origin master
