on:

  schedule:
    - cron: '0 * * * *'

  push:
    branches-ignore:
      - 'gh-pages'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: Roberbg97/baseball_cubans_news_generation@master

      - name: Update env var
        uses: allenevans/set-env@v1.0.0
        with:
          UPDATED: $(python -c "import os;print(open('UPDATE').read(),end='');os.remove('UPDATE')")
          overwrite: true

      - name: show UPDATE var
        run: |
          echo ${{env.UPDATE}}
          echo ${{env.UPDATE==false}}
          echo ${{contains(env.UPDATE, 'true')}}

      - name: deploy
        if: ${{env.UPDATE}}
        run: |
          git config --global user.name 'Roberbg97'
          git config --global user.email 'roberbg97@gmail.com'
          git add .
          git commit -am "Deploy apis"
          git push -f --set-upstream origin master
